require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

const fixes = {
  'Harry S. Truman Scholarship': { university: 'Truman Scholarship Foundation', funding: '$30,000', deadline: '2026-02-03', description: 'A prestigious merit-based award for college juniors committed to careers in public service. Supports graduate or professional school expenses.', requirements: 'US citizen; college junior; demonstrated commitment to public service; record of leadership and service.', official_link: 'https://www.truman.gov/apply/applying/2026-announcements' },
  'AAUW International Fellowships': { university: 'American Association of University Women', funding: '$20,000', deadline: '2026-09-17', description: 'Promotes education and equity for women by investing in international applicants pursuing graduate studies in STEM disciplines in the US.', requirements: "Non-US citizen or permanent resident; pursuing full-time postgraduate studies in STEM in the US; academic excellence; track record of empowering women.", official_link: 'https://www.aauw.org/resources/programs/fellowships-grants/aauw-international-fellowships/' },
  'UNESCO/Japan Young Researchers Fellowship': { university: 'UNESCO', funding: '$10,000', deadline: '2026-09-30', description: 'Fellowships for young researchers from Africa, SIDS, Ukraine and Türkiye to conduct postgraduate research in Japan on heritage conservation and sustainable development.', requirements: "Nationals of invited Member States; no more than 40 years old; Master's degree or equivalent; acceptance from a Japanese academic supervisor.", official_link: 'https://www.unesco.org/en/fellowships/keizo-obuchi' },
  'Barry Goldwater Scholarship': { university: 'Goldwater Scholarship Foundation', funding: '$7,500', deadline: '2026-01-31', description: 'Premier undergraduate scholarship for students intending to pursue research careers in natural sciences, engineering, or mathematics.', requirements: 'US citizen or permanent resident; college sophomore or junior; GPA >= 3.0; intend to pursue research in STEM.', official_link: 'https://goldwaterscholarship.gov/steps-in-process/' },
  'Dorrance Scholarship': { university: 'Dorrance Scholarship Programs', funding: '$12,000', deadline: '2026-02-04', description: 'Supports first-generation Arizona students who will be the first in their families to earn a four-year college degree.', requirements: 'Arizona resident; first-generation college student; minimum 3.0 GPA; minimum 1110 SAT / 22 ACT; plan to attend ASU, NAU, or UA.', official_link: 'https://dorrancescholarship.org/application/' },
  'DOE Nuclear Energy Undergraduate Scholarship': { university: 'US Department of Energy', funding: '$10,000', deadline: '2026-07-02', description: 'One-year scholarships for undergraduates pursuing science and engineering disciplines related to nuclear energy at US institutions.', requirements: 'US citizen or legal permanent resident; enrolled at a US college or university; pursuing nuclear energy-related degree; minimum 3.0 GPA.', official_link: 'https://neup.inl.gov/content/uploads/14/2026/05/FY-2025-UNLP-Scholarship-Request-for-Applications-Approved-2026-05-15.pdf' },
  'UNESCO/China Great Wall Fellowship': { university: 'UNESCO & Chinese Government', funding: '$15,000', deadline: '2026-01-23', description: "Co-sponsored fellowships for advanced studies at Chinese universities. Supports master's, doctoral, and visiting scholar programs across various fields.", requirements: "Nationals of invited developing Member States; bachelor's degree for Master's applicants; pre-admission letter from a Chinese university.", official_link: 'https://www.unesco.org/en/fellowships/greatwall' },
  'Bayer Foundation Scientific Fellowship': { university: 'Bayer Foundation', funding: '€10,000', deadline: '2026-04-15', description: 'Fellowships for outstanding master, PhD, and medical students to pursue international research projects and internships at German or international research institutions.', requirements: 'Enrolled master, PhD, or medical student; pursuing international research project or internship; placement at a German research institution or abroad.', official_link: 'https://www.bayer-foundation.com/fellowships-applications-our-fellowships-program-2026-are-now-open' },
  'Global Korea Scholarship': { university: 'Korean Government (NIIED)', funding: 'Full tuition + stipend', deadline: '2026-02-25', description: 'Fully funded scholarships for international students to study at Korean higher education institutions. Includes tuition, living expenses, airfare, and Korean language training.', requirements: 'Citizenship of NIIED designated countries; hold required degree or expected to graduate by July 31, 2026; TOPIK level 3 for degree programs.', official_link: 'https://www.studyinkorea.go.kr' },
  'IMU Breakout Graduate Fellowship': { university: 'International Mathematical Union', funding: '$10,000/year', deadline: '2026-05-30', description: 'Up to 4 years of funding for PhD students in mathematics from developing countries. Covers tuition, travel, living expenses, and research costs.', requirements: 'Citizen and resident of IMU-defined developing country; enrolled in PhD program in mathematical sciences; nominated by a qualified professor.', official_link: 'https://grants.mathunion.org/' },
  'Ireland Fellows Programme': { university: 'Irish Government (Irish Aid)', funding: 'Fully funded', deadline: '2026-07-28', description: "Fully funded Master's degree fellowship at an Irish university. Covers tuition, accommodation, travel, and monthly living allowance.", requirements: 'Citizen and resident of eligible country; commit to returning home after fellowship; meet English language requirements of chosen Irish university.', official_link: 'https://opportunitiesnexus.com/ireland-fellows-programme-2026-2027/' },
  'University of Tokyo Todai Fellowship': { university: 'University of Tokyo', funding: '¥200,000/month', deadline: '2026-06-10', description: 'Fellowship for international doctoral students at the University of Tokyo Graduate School of Frontier Sciences. Provides monthly stipend and research support.', official_link: 'https://www.k.u-tokyo.ac.jp/en/assets/files/TodaiFellow_2026_EN_Aver.2_0526.pdf', requirements: 'Applying for admission to doctoral course at UTokyo Graduate School of Frontier Sciences; valid student visa for Japan; not receiving other scholarships.' },
};

async function update() {
  for (const [title, fields] of Object.entries(fixes)) {
    const { error } = await supabase.from('scholarships').update(fields).eq('title', title);
    if (error) console.log('Error:', title, error.message);
    else console.log('Updated:', title);
  }
  const { data } = await supabase.from('scholarships').select('title, funding, official_link').order('title');
  console.log('\nFinal state:');
  data.forEach(r => console.log(`  ${r.title}: ${r.funding} | ${r.official_link.substring(0, 60)}...`));
}

update();
