/*
# Seed scholarship catalog

Populates the `scholarships` table with a realistic starter catalog so the
Browse/Saved/Dashboard/AI-eligibility surfaces have data to render from day
one. Idempotent: uses ON CONFLICT DO NOTHING on a stable (title, provider)
pair so re-running won't create duplicates.

Categories covered: merit, need-based, STEM, international, women in tech,
undergraduate, graduate, community leadership. Deadlines span the next ~9
months from the seed date.
*/

INSERT INTO scholarships (title, provider, description, amount, amount_type, deadline, country, field_of_study, education_level, min_gpa, eligibility_criteria, application_url, tags) VALUES
('Future Leaders Merit Scholarship', 'National Scholars Foundation', 'A prestigious merit-based award recognizing undergraduate students who demonstrate exceptional academic achievement and leadership potential.', 15000, 'fixed', '2026-03-15', 'United States', 'Any', 'Undergraduate', 3.5, 'US citizen or permanent resident; enrolled full-time at an accredited US institution; minimum 3.5 GPA; demonstrated leadership.', 'https://example.com/apply/future-leaders', ARRAY['merit','leadership','undergraduate']),
('Women in STEM Excellence Award', 'TechForward Foundation', 'Empowering women pursuing degrees in science, technology, engineering, or mathematics with funding and mentorship.', 12000, 'fixed', '2026-04-30', 'United States', 'STEM', 'Undergraduate', 3.2, 'Identify as a woman; enrolled in an accredited STEM program; minimum 3.2 GPA; US-based institution.', 'https://example.com/apply/women-stem', ARRAY['stem','women','undergraduate']),
('Global Innovators Graduate Fellowship', 'World Education Trust', 'A competitive fellowship for international graduate students conducting research with real-world impact.', 25000, 'fixed', '2026-02-28', 'International', 'Research', 'Graduate', 3.6, 'Enrolled in a graduate program; research proposal required; open to international students studying anywhere.', 'https://example.com/apply/global-innovators', ARRAY['graduate','international','research']),
('Community Changemaker Grant', 'Local Impact Fund', 'Supporting students who lead meaningful community service initiatives while pursuing their education.', 5000, 'fixed', '2026-05-20', 'United States', 'Any', 'Undergraduate', 2.8, 'Documented community service history; enrolled or accepted at an accredited institution; personal statement required.', 'https://example.com/apply/changemaker', ARRAY['community','service','need-aware']),
('Excellence in Computer Science Award', 'CodeTheFuture Inc.', 'Recognizing outstanding computer science students with a passion for building software that matters.', 10000, 'fixed', '2026-06-10', 'United States', 'Computer Science', 'Undergraduate', 3.4, 'CS or related major; portfolio of projects; enrolled full-time; US institution.', 'https://example.com/apply/cs-excellence', ARRAY['stem','computer-science','undergraduate']),
('First-Generation Achievement Scholarship', 'Pathway Scholars', 'Dedicated to students who are the first in their family to attend college, easing the financial path to a degree.', 8000, 'fixed', '2026-03-30', 'United States', 'Any', 'Undergraduate', 2.5, 'First-generation college student; US resident; enrolled or accepted at an accredited institution.', 'https://example.com/apply/first-gen', ARRAY['first-generation','need-aware','undergraduate']),
('Healthcare Heroes Scholarship', 'MedCare Foundation', 'For students committed to a career in healthcare, nursing, or public health.', 18000, 'fixed', '2026-07-15', 'United States', 'Healthcare', 'Graduate', 3.3, 'Enrolled in a healthcare-related program; intent to practice in the US; two recommendation letters.', 'https://example.com/apply/healthcare-heroes', ARRAY['healthcare','graduate']),
('International Student Excellence Award', 'Global Reach Education', 'Helping outstanding international students fund their US education.', 20000, 'fixed', '2026-04-15', 'United States', 'Any', 'Undergraduate', 3.5, 'Holds a valid international student visa; enrolled full-time at a US institution; minimum 3.5 GPA.', 'https://example.com/apply/intl-excellence', ARRAY['international','undergraduate']),
('Creative Arts Visionary Grant', 'Artistic Futures', 'Funding for students in visual arts, design, music, and performing arts to develop a portfolio project.', 7000, 'fixed', '2026-05-05', 'United States', 'Arts', 'Undergraduate', 2.8, 'Arts major; portfolio submission required; enrolled at an accredited institution.', 'https://example.com/apply/arts-visionary', ARRAY['arts','creative','undergraduate']),
('Veterans Education Support Fund', 'Honor Foundation', 'Honoring military veterans and active-duty service members pursuing higher education.', 14000, 'fixed', '2026-08-01', 'United States', 'Any', 'Undergraduate', 2.5, 'Veteran or active-duty service member; enrolled or accepted at an accredited US institution.', 'https://example.com/apply/veterans-fund', ARRAY['veterans','service']),
('Data Science Pioneers Fellowship', 'DataMinds Lab', 'A fellowship for graduate students pushing the boundaries of data science and machine learning research.', 22000, 'stipend', '2026-06-25', 'United States', 'Data Science', 'Graduate', 3.6, 'Enrolled in a data science / ML graduate program; research statement; faculty endorsement.', 'https://example.com/apply/data-pioneers', ARRAY['stem','graduate','data-science','research']),
('Sustainability & Climate Action Scholarship', 'Green Future Trust', 'For students whose studies or projects advance environmental sustainability and climate solutions.', 9000, 'fixed', '2026-04-22', 'International', 'Environmental Science', 'Undergraduate', 3.0, 'Enrolled in a sustainability-related program or with a relevant project; open to international applicants.', 'https://example.com/apply/climate-action', ARRAY['environment','sustainability','international','undergraduate'])
ON CONFLICT DO NOTHING;
