/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#e5eeff',
        'primary-container': '#1a2b48',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#5a00c6',
        'inverse-primary': '#b6c7eb',
        secondary: '#006591',
        'on-primary': '#ffffff',
        primary: '#031632',
        'on-error-container': '#93000a',
        'tertiary-container': '#380081',
        'surface-container-high': '#dce9ff',
        'tertiary-fixed-dim': '#d2bbff',
        'surface-dim': '#cbdbf5',
        'surface-container-low': '#eff4ff',
        'primary-fixed-dim': '#b6c7eb',
        'surface-bright': '#f8f9ff',
        'on-primary-fixed': '#081b38',
        background: '#f8f9ff',
        'on-surface-variant': '#44474d',
        'secondary-fixed': '#c9e6ff',
        'on-secondary-container': '#004666',
        'secondary-fixed-dim': '#89ceff',
        'on-background': '#0b1c30',
        'on-tertiary-fixed': '#25005a',
        'on-tertiary-container': '#a579ff',
        'inverse-surface': '#213145',
        'on-primary-container': '#8293b5',
        'outline-variant': '#c5c6ce',
        'on-primary-fixed-variant': '#374765',
        'on-secondary-fixed-variant': '#004c6e',
        tertiary: '#1f004e',
        'surface-tint': '#4e5f7e',
        'on-secondary-fixed': '#001e2f',
        'on-error': '#ffffff',
        surface: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        error: '#ba1a1a',
        'primary-fixed': '#d7e2ff',
        outline: '#75777e',
        'tertiary-fixed': '#eaddff',
        'secondary-container': '#39b8fd',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        xs: '4px',
        sm: '8px',
        base: '8px',
        lg: '24px',
        xl: '40px',
        gutter: '24px',
        md: '16px',
      },
      fontFamily: {
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-sm': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-sm': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-md': ['Hanken Grotesk', 'sans-serif'],
        sans: ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
